# Generated by Django 6.0.5 on 2026-05-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('paginas', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
                ('data_publicacao', models.DateField()),
            ],
        ),
    ]
