# Generated by Django 6.0.5 on 2026-05-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('calorias', models.IntegerField()),
                ('vegetariana', models.BooleanField(default=False)),
                ('data_planejada', models.DateField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
